version: '2'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432

  web:
    build: .
    environment:
      BUNDLE_PATH: '/bundle'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
    volumes:
      - .:/app
      - bundle:/bundle
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    links:
      - db

volumes:
  db:
  bundle:
