default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost # postgres if you are using docker
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: car_dealership_sm_dev

test:
  <<: *default
  database: car_dealership_sm_test

production:
  <<: *default
  database: car_dealership_sm
